load("@com_github_bazelbuild_buildtools//buildifier:def.bzl", "buildifier")
load("@initialize_toolchain//:defs.bzl", "clang_format", "clang_tidy", "compile_commands")

# -- Load autogenerated target lists
load("//tools/target_lists:targets.bzl", "ALL_TARGETS", "TIDY_TARGETS")

exports_files([
    ".clang-format",
    ".clang-tidy",
])

# -- Compile commands

compile_commands(
    name = "compile_commands",
    indent = False,
    targets = ALL_TARGETS,
)

# -- Buildifier

buildifier(
    name = "buildifier_check",
    # exclude_patterns = ["glob-pattern", ...]
    lint_mode = "warn",
    verbose = False,
)

buildifier(
    name = "buildifier_fix",
    # exclude_patterns = ["glob-pattern", ...]
    lint_mode = "fix",
    verbose = True,
)

# -- Clang Format
# These rules are an EXAMPLE, and not used by the `tools/run_clang_format.sh` script
filegroup(
    name = "clang_format_config",
    srcs = [".clang-format"],
)

alias(
    name = "clang_format_bin",
    actual = "@initialize_toolchain//:clang_format_bin",
)

clang_format(
    name = "format_check",
    clang_format = ":clang_format_bin",
    config_file = ":clang_format_config",
    mode = "check",
    targets = ALL_TARGETS,
)

clang_format(
    name = "format_fix",
    clang_format = ":clang_format_bin",
    config_file = ":clang_format_config",
    mode = "fix",
    targets = ALL_TARGETS,
)

# -- Clang Tidy

filegroup(
    name = "clang_tidy_config",
    srcs = [".clang-tidy"],
)

alias(
    name = "clang_tidy_bin",  # Pass through to whatever clang-tidy is installed
    actual = "@initialize_toolchain//:clang_tidy_bin",
)

clang_tidy(
    name = "static_analysis",
    clang_tidy = ":clang_tidy_bin",
    config_file = ":clang_tidy_config",
    targets = TIDY_TARGETS,
)
