"""
This file is regenerated by calling the 'refresh.sh' script. This script should
be rerun before running clang-tidy, clang-format, or refresh-compile-commands
whenever a new target may have been added. To ensure that these tools always work
as expected, run 'refresh.sh' in the makefile before the specified tool.
"""

ALL_TARGETS = [
    "//example/config/suppressions:all",
    "//example/src:main",
    "//example/src:some_lib_lib",
]

TIDY_TARGETS = ALL_TARGETS
